### ISSUE TITLE
Is there a js file to test it?

### ISSUE THREAD

**Issue by onigetoc** [post-programming/videojs-landscape-fullscreen#10]
Is there a js file to test it?
I do not use node or gulp, i hate it
It would not be that hard to put a rendered file in src....

**Comment by prateekrastogi** [comment]
Though I would like to put a rendered markup, but it sounds too fishy for the lack of upstream & downstream data integrity mechanisms. Perhaps, right place to do so would be create another issue to allow dynamic plugin mutations in [video.js](https://videojs.com/getting-started)
