### ISSUE TITLE
How to get the *.min.js file

### ISSUE THREAD

**Issue by veritme** [post-programming/videojs-landscape-fullscreen#12]
Some tutorial to get the * .min.js file I don't know how to use npm / yarn to build the file, my page is pure html

**Comment by prateekrastogi** [comment]
Thanks for bringing this issue to my attention. Had to clean upstream code dump. Here's your URL: https://www.jsdelivr.com/package/npm/videojs-landscape-fullscreen?version=1.2.3

Also, do consider contributing to https://github.com/paxos-raft/paxos-raft, if this project helped you.

**Comment by enmaskarado** [comment]
Hello,
I tried to use this URL:
https://cdn.jsdelivr.net/npm/videojs-landscape-fullscreen@1.2.6/dist/videojs-landscape-fullscreen.min.js

The browser breaks and shows errors like "ReferenceError: exports is not defined" and "player.landscapeFullscreen is not a function".

I have manually reviewed the contents of "videojs-landscape-fullscreen.min.js" and I see that the file is not properly compiled and that it still has nodejs functions (require(), exports, etc).

**Comment by prateekrastogi** [comment]
You have to wait for video.js player object to load and initialize  for "player.landscapeFullscreen" to function as intended. 

It uses https://babeljs.io/docs/en/babel-preset-env, which as per as its documentation polyfills browser module `functions`.  

Please let me know module type you are using in your browser as both video.js and my plugin are using same babel config for .min.js compilation.

**Comment by enmaskarado** [comment]
Thanks for the response.
Like the original issue pointed by @veritme, I only want a "videojs-landscape-fullscreen.min.js" suitable for embed with <script> in standard HTML web pages.

I used to use the old version "https://cdn.jsdelivr.net/npm/videojs-landscape-fullscreen@1.1.1/dist/videojs-landscape-fullscreen.min.js" but now that URl returns 404.

**Comment by prateekrastogi** [comment]
@enmaskarado  Thanks for your response. I upgraded to babel for transpilation of my js but was not bundling my modules. Just, pushed a new minor release. Everything will work properly.

**Comment by prateekrastogi** [comment]
@enmaskarado  Also, do gather some courage for https://github.com/paxos-raft/paxos-raft to carry forward future of programming.

**Comment by enmaskarado** [comment]
I'm using https://cdn.jsdelivr.net/npm/videojs-landscape-fullscreen@1.4.6/dist/videojs-landscape-fullscreen.min.js now and works well! Thanks!
