### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by EhsanCh** [post-programming/videojs-landscape-fullscreen#13]
On Firefox 68.5.0 for android :
1- player wont enter to fullscreen when rotate to landscape
2- when exit from fullscreen , rotation remain in landscape even while phone is portrate.

Also, it should check video dimensions and for Vertical video. for them.

**Comment by prateekrastogi** [comment]
Please share your code sandbox along with test run.

**Comment by EhsanCh** [comment]
i ran with latest videojs with latest plugin version in dist folder.
```
<script src="//path/to/video.min.js"></script>
<script src="//path/to/videojs-landscape-fullscreen.min.js"></script>
<script>
  var player = videojs('some-player-id');

  player.landscapeFullscreen();
</script>
```

**Comment by prateekrastogi** [comment]
Please share your console output upon running this code.

**Comment by biozshock** [comment]
Firefox gives an error "DOMException: "The operation is insecure."" on the orientation.lock error handler.

Also fullscreen is not activated due to "Request for fullscreen was denied because Element.requestFullscreen() was not called from inside a short running user-generated event handler.", though MDN states that orientationchange is allowed.

**Comment by prateekrastogi** [comment]
@biozshock  Here's the script you are loading https://observant-brainy-ant.glitch.me/script.js

**Comment by biozshock** [comment]
@prateekrastogi yes. Played a bit after posting. Commenting out proper listener assignment will do the job. Works well in Chrome but does give an error in Firefox.

**Comment by prateekrastogi** [comment]
@biozshock  niche approach but html5 .mp4 has its own caveats. Do video.js on hls for proper web app.
