### ISSUE TITLE
The player is broken

### ISSUE THREAD

**Issue by danichim** [post-programming/videojs-landscape-fullscreen#14]
In the console log no errors, [codesandbox](https://codesandbox.io/s/videojs-landscape-fullscreen-yqlpm)

I use the code from readme just copy & paste, nothing special.

What is the problem there?

**Comment by prateekrastogi** [comment]
How are you bundling css within a react app with this codesandbox? Please consider first running a video.js on react without this plugin using these instructions from the same source.

It's often mixing these two things together yields such problems.

**Comment by prateekrastogi** [comment]
Even player controls are displayed on right clicking this sandbox. Make sure that player controls are displayed and loaded.

**Comment by danichim** [comment]
Is your code from demo what?
