### ISSUE TITLE
the height of a MP4 video overflowed on fullscreen

### ISSUE THREAD

**Issue by sdrkyj** [post-programming/videojs-landscape-fullscreen#18]
as of the title, the height of a MP4 video overflowed on fullscreen. see the bottom of http://sdrkyj.top/
but it's ok of m3u8 .ts video.

**Comment by prateekrastogi** [comment]
Consult video.js documentation for how to adjust height. I believe you were misguided from a discussion in one of the issue promoting browser DOM .requestFullscreen() API Usage.  Referencing that issue below:

https://github.com/prateekrastogi/videojs-landscape-fullscreen/issues/13
