### ISSUE TITLE
react-next use videojs-landscape-fullscreen warning Cannot set property 'lockOrientationUniversal' of undefined

### ISSUE THREAD

**Issue by lvqi0724** [post-programming/videojs-landscape-fullscreen#20]
![image](https://user-images.githubusercontent.com/50160159/103097313-cd881c00-4641-11eb-9c43-b083905bd0b9.png)
![image](https://user-images.githubusercontent.com/50160159/103097327-d842b100-4641-11eb-853b-703b272f7a44.png)

**Comment by prateekrastogi** [comment]
Use webpack imports properly; module not detected.

**Comment by lvqi0724** [comment]
wtf??????????????????????

**Comment by lvqi0724** [comment]
Baby tell me what to do

**Comment by lvqi0724** [comment]
> Use webpack imports properly; module not detected.
