### ISSUE TITLE
When the app is set to portrait mode I can't enter fullscreen on rotate to landscape

### ISSUE THREAD

**Issue by Milos-CPBS** [post-programming/videojs-landscape-fullscreen#5]
Dear Developer,

If I set up the orientation of the react app to portrait mode in app.json I can't enter the fullscreen on rotate to landscape. If I understand correctly the option alwaysInLandscapeMode: true, should allow to do that? It's not working on the iOS and either on the Android. If I set up the orientation:  default, then it works nice on Android, but on iOS fullscreen rotation breaks my layout. Could you please help me to make it work even when orientation is set up to portrait?

The app is using webview to show the video player located on the server and made of video.js.

Thank you in advance
Milos

**Comment by prateekrastogi** [comment]
kindly share your react code

**Comment by Milos-CPBS** [comment]
Hi,

let me clarify few things: it's a React-native aplication which is loading bare videojs player as a webpage in WebView.
I prepared a snack for you to try:
[videojs-fulscreen-landscape test](https://snack.expo.io/@milosh/webview-test)

Thank you
M.

**Comment by prateekrastogi** [comment]
Unfortunately, WebView doesn't provide the native browser device orientation api. So, it's won't work.
Here's the link of WebView broader specs:

https://developer.chrome.com/multidevice/webview/overview 

Feel free to create a pull request, if you find a workaround.
